// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/login/domain.proto

package login

import (
	user "github.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Initials      string                 `protobuf:"bytes,4,opt,name=initials,proto3" json:"initials,omitempty"`
	Org           string                 `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_login_domain_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetInitials() string {
	if x != nil {
		return x.Initials
	}
	return ""
}

func (x *RegisterRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_login_domain_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *user.User             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_login_domain_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetInfo() *user.User {
	if x != nil {
		return x.Info
	}
	return nil
}

type DeviceLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceLoginResponse) Reset() {
	*x = DeviceLoginResponse{}
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLoginResponse) ProtoMessage() {}

func (x *DeviceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_login_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLoginResponse.ProtoReflect.Descriptor instead.
func (*DeviceLoginResponse) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_login_domain_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceLoginResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

var File_xyz_fire_step_v1_login_domain_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_login_domain_proto_rawDesc = "" +
	"\n" +
	"#xyz/fire-step/v1/login/domain.proto\x12\x16xyz.fire_step.v1.login\x1a\"xyz/fire-step/v1/user/domain.proto\"\x8d\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\binitials\x18\x04 \x01(\tR\binitials\x12\x10\n" +
	"\x03org\x18\x05 \x01(\tR\x03org\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\rLoginResponse\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.xyz.fire_step.v1.user.UserR\x04info\"/\n" +
	"\x13DeviceLoginResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asessionBtZPgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/login;login\xaa\x02\x1fAesterial.FireStep.Api.V1.Loginb\x06proto3"

var (
	file_xyz_fire_step_v1_login_domain_proto_rawDescOnce sync.Once
	file_xyz_fire_step_v1_login_domain_proto_rawDescData []byte
)

func file_xyz_fire_step_v1_login_domain_proto_rawDescGZIP() []byte {
	file_xyz_fire_step_v1_login_domain_proto_rawDescOnce.Do(func() {
		file_xyz_fire_step_v1_login_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_login_domain_proto_rawDesc), len(file_xyz_fire_step_v1_login_domain_proto_rawDesc)))
	})
	return file_xyz_fire_step_v1_login_domain_proto_rawDescData
}

var file_xyz_fire_step_v1_login_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xyz_fire_step_v1_login_domain_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: xyz.fire_step.v1.login.RegisterRequest
	(*LoginRequest)(nil),        // 1: xyz.fire_step.v1.login.LoginRequest
	(*LoginResponse)(nil),       // 2: xyz.fire_step.v1.login.LoginResponse
	(*DeviceLoginResponse)(nil), // 3: xyz.fire_step.v1.login.DeviceLoginResponse
	(*user.User)(nil),           // 4: xyz.fire_step.v1.user.User
}
var file_xyz_fire_step_v1_login_domain_proto_depIdxs = []int32{
	4, // 0: xyz.fire_step.v1.login.LoginResponse.info:type_name -> xyz.fire_step.v1.user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_login_domain_proto_init() }
func file_xyz_fire_step_v1_login_domain_proto_init() {
	if File_xyz_fire_step_v1_login_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_login_domain_proto_rawDesc), len(file_xyz_fire_step_v1_login_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_fire_step_v1_login_domain_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_login_domain_proto_depIdxs,
		MessageInfos:      file_xyz_fire_step_v1_login_domain_proto_msgTypes,
	}.Build()
	File_xyz_fire_step_v1_login_domain_proto = out.File
	file_xyz_fire_step_v1_login_domain_proto_goTypes = nil
	file_xyz_fire_step_v1_login_domain_proto_depIdxs = nil
}
