// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/user/domain.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Initials      string                 `protobuf:"bytes,3,opt,name=initials,proto3" json:"initials,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Org           string                 `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`
	Joined        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_xyz_fire_step_v1_user_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_user_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_user_domain_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetInitials() string {
	if x != nil {
		return x.Initials
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *User) GetJoined() *timestamppb.Timestamp {
	if x != nil {
		return x.Joined
	}
	return nil
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*User                `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_xyz_fire_step_v1_user_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_user_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_user_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Users) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

var File_xyz_fire_step_v1_user_domain_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_user_domain_proto_rawDesc = "" +
	"\n" +
	"\"xyz/fire-step/v1/user/domain.proto\x12\x15xyz.fire_step.v1.user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\binitials\x18\x03 \x01(\tR\binitials\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x10\n" +
	"\x03org\x18\x05 \x01(\tR\x03org\x122\n" +
	"\x06joined\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06joined\"8\n" +
	"\x05Users\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.xyz.fire_step.v1.user.UserR\x04listBqZNgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/user;user\xaa\x02\x1eAesterial.FireStep.Api.V1.Userb\x06proto3"

var (
	file_xyz_fire_step_v1_user_domain_proto_rawDescOnce sync.Once
	file_xyz_fire_step_v1_user_domain_proto_rawDescData []byte
)

func file_xyz_fire_step_v1_user_domain_proto_rawDescGZIP() []byte {
	file_xyz_fire_step_v1_user_domain_proto_rawDescOnce.Do(func() {
		file_xyz_fire_step_v1_user_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_user_domain_proto_rawDesc), len(file_xyz_fire_step_v1_user_domain_proto_rawDesc)))
	})
	return file_xyz_fire_step_v1_user_domain_proto_rawDescData
}

var file_xyz_fire_step_v1_user_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xyz_fire_step_v1_user_domain_proto_goTypes = []any{
	(*User)(nil),                  // 0: xyz.fire_step.v1.user.User
	(*Users)(nil),                 // 1: xyz.fire_step.v1.user.Users
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_xyz_fire_step_v1_user_domain_proto_depIdxs = []int32{
	2, // 0: xyz.fire_step.v1.user.User.joined:type_name -> google.protobuf.Timestamp
	0, // 1: xyz.fire_step.v1.user.Users.list:type_name -> xyz.fire_step.v1.user.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_user_domain_proto_init() }
func file_xyz_fire_step_v1_user_domain_proto_init() {
	if File_xyz_fire_step_v1_user_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_user_domain_proto_rawDesc), len(file_xyz_fire_step_v1_user_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_fire_step_v1_user_domain_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_user_domain_proto_depIdxs,
		MessageInfos:      file_xyz_fire_step_v1_user_domain_proto_msgTypes,
	}.Build()
	File_xyz_fire_step_v1_user_domain_proto = out.File
	file_xyz_fire_step_v1_user_domain_proto_goTypes = nil
	file_xyz_fire_step_v1_user_domain_proto_depIdxs = nil
}
