// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/stats/service.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_xyz_fire_step_v1_stats_service_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_stats_service_proto_rawDesc = "" +
	"\n" +
	"$xyz/fire-step/v1/stats/service.proto\x12\x16xyz.fire_step.v1.statsBtZPgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/stats;stats\xaa\x02\x1fAesterial.FireStep.Api.V1.Statsb\x06proto3"

var file_xyz_fire_step_v1_stats_service_proto_goTypes = []any{}
var file_xyz_fire_step_v1_stats_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_stats_service_proto_init() }
func file_xyz_fire_step_v1_stats_service_proto_init() {
	if File_xyz_fire_step_v1_stats_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_stats_service_proto_rawDesc), len(file_xyz_fire_step_v1_stats_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_fire_step_v1_stats_service_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_stats_service_proto_depIdxs,
	}.Build()
	File_xyz_fire_step_v1_stats_service_proto = out.File
	file_xyz_fire_step_v1_stats_service_proto_goTypes = nil
	file_xyz_fire_step_v1_stats_service_proto_depIdxs = nil
}
