// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/seances/domain.proto

package seances

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Seance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Errors        int32                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	ActionsJson   string                 `protobuf:"bytes,4,opt,name=actionsJson,proto3" json:"actionsJson,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	Done          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seance) Reset() {
	*x = Seance{}
	mi := &file_xyz_fire_step_v1_seances_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seance) ProtoMessage() {}

func (x *Seance) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_seances_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seance.ProtoReflect.Descriptor instead.
func (*Seance) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_seances_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Seance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seance) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Seance) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *Seance) GetActionsJson() string {
	if x != nil {
		return x.ActionsJson
	}
	return ""
}

func (x *Seance) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Seance) GetDone() *timestamppb.Timestamp {
	if x != nil {
		return x.Done
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_xyz_fire_step_v1_seances_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_seances_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_seances_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Action) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type Seances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Seance              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seances) Reset() {
	*x = Seances{}
	mi := &file_xyz_fire_step_v1_seances_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seances) ProtoMessage() {}

func (x *Seances) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_seances_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seances.ProtoReflect.Descriptor instead.
func (*Seances) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_seances_domain_proto_rawDescGZIP(), []int{2}
}

func (x *Seances) GetList() []*Seance {
	if x != nil {
		return x.List
	}
	return nil
}

var File_xyz_fire_step_v1_seances_domain_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_seances_domain_proto_rawDesc = "" +
	"\n" +
	"%xyz/fire-step/v1/seances/domain.proto\x12\x18xyz.fire_step.v1.seances\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x01\n" +
	"\x06Seance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\tR\aownerId\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x05R\x06errors\x12 \n" +
	"\vactionsJson\x18\x04 \x01(\tR\vactionsJson\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12.\n" +
	"\x04done\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04done\"\\\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"?\n" +
	"\aSeances\x124\n" +
	"\x04list\x18\x01 \x03(\v2 .xyz.fire_step.v1.seances.SeanceR\x04listBzZTgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/seances;seances\xaa\x02!Aesterial.FireStep.Api.V1.Seancesb\x06proto3"

var (
	file_xyz_fire_step_v1_seances_domain_proto_rawDescOnce sync.Once
	file_xyz_fire_step_v1_seances_domain_proto_rawDescData []byte
)

func file_xyz_fire_step_v1_seances_domain_proto_rawDescGZIP() []byte {
	file_xyz_fire_step_v1_seances_domain_proto_rawDescOnce.Do(func() {
		file_xyz_fire_step_v1_seances_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_seances_domain_proto_rawDesc), len(file_xyz_fire_step_v1_seances_domain_proto_rawDesc)))
	})
	return file_xyz_fire_step_v1_seances_domain_proto_rawDescData
}

var file_xyz_fire_step_v1_seances_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xyz_fire_step_v1_seances_domain_proto_goTypes = []any{
	(*Seance)(nil),                // 0: xyz.fire_step.v1.seances.Seance
	(*Action)(nil),                // 1: xyz.fire_step.v1.seances.Action
	(*Seances)(nil),               // 2: xyz.fire_step.v1.seances.Seances
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_xyz_fire_step_v1_seances_domain_proto_depIdxs = []int32{
	3, // 0: xyz.fire_step.v1.seances.Seance.at:type_name -> google.protobuf.Timestamp
	3, // 1: xyz.fire_step.v1.seances.Seance.done:type_name -> google.protobuf.Timestamp
	3, // 2: xyz.fire_step.v1.seances.Action.at:type_name -> google.protobuf.Timestamp
	0, // 3: xyz.fire_step.v1.seances.Seances.list:type_name -> xyz.fire_step.v1.seances.Seance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_seances_domain_proto_init() }
func file_xyz_fire_step_v1_seances_domain_proto_init() {
	if File_xyz_fire_step_v1_seances_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_seances_domain_proto_rawDesc), len(file_xyz_fire_step_v1_seances_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_fire_step_v1_seances_domain_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_seances_domain_proto_depIdxs,
		MessageInfos:      file_xyz_fire_step_v1_seances_domain_proto_msgTypes,
	}.Build()
	File_xyz_fire_step_v1_seances_domain_proto = out.File
	file_xyz_fire_step_v1_seances_domain_proto_goTypes = nil
	file_xyz_fire_step_v1_seances_domain_proto_depIdxs = nil
}
