// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/seances/service.proto

package seances

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSeanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Errors        int32                  `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	Done          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeanceRequest) Reset() {
	*x = CreateSeanceRequest{}
	mi := &file_xyz_fire_step_v1_seances_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeanceRequest) ProtoMessage() {}

func (x *CreateSeanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_seances_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeanceRequest.ProtoReflect.Descriptor instead.
func (*CreateSeanceRequest) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_seances_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSeanceRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CreateSeanceRequest) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *CreateSeanceRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *CreateSeanceRequest) GetDone() *timestamppb.Timestamp {
	if x != nil {
		return x.Done
	}
	return nil
}

var File_xyz_fire_step_v1_seances_service_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_seances_service_proto_rawDesc = "" +
	"\n" +
	"&xyz/fire-step/v1/seances/service.proto\x12\x18xyz.fire_step.v1.seances\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%xyz/fire-step/v1/seances/domain.proto\"\xc5\x01\n" +
	"\x13CreateSeanceRequest\x12:\n" +
	"\aactions\x18\x01 \x03(\v2 .xyz.fire_step.v1.seances.ActionR\aactions\x12\x16\n" +
	"\x06errors\x18\x02 \x01(\x05R\x06errors\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12.\n" +
	"\x04done\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04done2\xae\x01\n" +
	"\x0eSeancesService\x12A\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a!.xyz.fire_step.v1.seances.Seances\x12Y\n" +
	"\x06Create\x12-.xyz.fire_step.v1.seances.CreateSeanceRequest\x1a .xyz.fire_step.v1.seances.SeanceBzZTgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/seances;seances\xaa\x02!Aesterial.FireStep.Api.V1.Seancesb\x06proto3"

var (
	file_xyz_fire_step_v1_seances_service_proto_rawDescOnce sync.Once
	file_xyz_fire_step_v1_seances_service_proto_rawDescData []byte
)

func file_xyz_fire_step_v1_seances_service_proto_rawDescGZIP() []byte {
	file_xyz_fire_step_v1_seances_service_proto_rawDescOnce.Do(func() {
		file_xyz_fire_step_v1_seances_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_seances_service_proto_rawDesc), len(file_xyz_fire_step_v1_seances_service_proto_rawDesc)))
	})
	return file_xyz_fire_step_v1_seances_service_proto_rawDescData
}

var file_xyz_fire_step_v1_seances_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xyz_fire_step_v1_seances_service_proto_goTypes = []any{
	(*CreateSeanceRequest)(nil),   // 0: xyz.fire_step.v1.seances.CreateSeanceRequest
	(*Action)(nil),                // 1: xyz.fire_step.v1.seances.Action
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
	(*Seances)(nil),               // 4: xyz.fire_step.v1.seances.Seances
	(*Seance)(nil),                // 5: xyz.fire_step.v1.seances.Seance
}
var file_xyz_fire_step_v1_seances_service_proto_depIdxs = []int32{
	1, // 0: xyz.fire_step.v1.seances.CreateSeanceRequest.actions:type_name -> xyz.fire_step.v1.seances.Action
	2, // 1: xyz.fire_step.v1.seances.CreateSeanceRequest.at:type_name -> google.protobuf.Timestamp
	2, // 2: xyz.fire_step.v1.seances.CreateSeanceRequest.done:type_name -> google.protobuf.Timestamp
	3, // 3: xyz.fire_step.v1.seances.SeancesService.List:input_type -> google.protobuf.Empty
	0, // 4: xyz.fire_step.v1.seances.SeancesService.Create:input_type -> xyz.fire_step.v1.seances.CreateSeanceRequest
	4, // 5: xyz.fire_step.v1.seances.SeancesService.List:output_type -> xyz.fire_step.v1.seances.Seances
	5, // 6: xyz.fire_step.v1.seances.SeancesService.Create:output_type -> xyz.fire_step.v1.seances.Seance
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_seances_service_proto_init() }
func file_xyz_fire_step_v1_seances_service_proto_init() {
	if File_xyz_fire_step_v1_seances_service_proto != nil {
		return
	}
	file_xyz_fire_step_v1_seances_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_seances_service_proto_rawDesc), len(file_xyz_fire_step_v1_seances_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_fire_step_v1_seances_service_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_seances_service_proto_depIdxs,
		MessageInfos:      file_xyz_fire_step_v1_seances_service_proto_msgTypes,
	}.Build()
	File_xyz_fire_step_v1_seances_service_proto = out.File
	file_xyz_fire_step_v1_seances_service_proto_goTypes = nil
	file_xyz_fire_step_v1_seances_service_proto_depIdxs = nil
}
