// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: xyz/fire-step/v1/seances/service.proto

package seances

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeancesService_List_FullMethodName   = "/xyz.fire_step.v1.seances.SeancesService/List"
	SeancesService_Create_FullMethodName = "/xyz.fire_step.v1.seances.SeancesService/Create"
)

// SeancesServiceClient is the client API for SeancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeancesServiceClient interface {
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Seances, error)
	Create(ctx context.Context, in *CreateSeanceRequest, opts ...grpc.CallOption) (*Seance, error)
}

type seancesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeancesServiceClient(cc grpc.ClientConnInterface) SeancesServiceClient {
	return &seancesServiceClient{cc}
}

func (c *seancesServiceClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Seances, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Seances)
	err := c.cc.Invoke(ctx, SeancesService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seancesServiceClient) Create(ctx context.Context, in *CreateSeanceRequest, opts ...grpc.CallOption) (*Seance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Seance)
	err := c.cc.Invoke(ctx, SeancesService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeancesServiceServer is the server API for SeancesService service.
// All implementations should embed UnimplementedSeancesServiceServer
// for forward compatibility.
type SeancesServiceServer interface {
	List(context.Context, *emptypb.Empty) (*Seances, error)
	Create(context.Context, *CreateSeanceRequest) (*Seance, error)
}

// UnimplementedSeancesServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeancesServiceServer struct{}

func (UnimplementedSeancesServiceServer) List(context.Context, *emptypb.Empty) (*Seances, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSeancesServiceServer) Create(context.Context, *CreateSeanceRequest) (*Seance, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSeancesServiceServer) testEmbeddedByValue() {}

// UnsafeSeancesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeancesServiceServer will
// result in compilation errors.
type UnsafeSeancesServiceServer interface {
	mustEmbedUnimplementedSeancesServiceServer()
}

func RegisterSeancesServiceServer(s grpc.ServiceRegistrar, srv SeancesServiceServer) {
	// If the following call panics, it indicates UnimplementedSeancesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeancesService_ServiceDesc, srv)
}

func _SeancesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeancesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeancesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeancesServiceServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeancesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSeanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeancesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeancesService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeancesServiceServer).Create(ctx, req.(*CreateSeanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeancesService_ServiceDesc is the grpc.ServiceDesc for SeancesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeancesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xyz.fire_step.v1.seances.SeancesService",
	HandlerType: (*SeancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SeancesService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SeancesService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xyz/fire-step/v1/seances/service.proto",
}
