// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/session/domain.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_UNSPECIFIED DeviceType = 0
	DeviceType_CLIENT      DeviceType = 1
	DeviceType_WEB         DeviceType = 2
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CLIENT",
		2: "WEB",
	}
	DeviceType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CLIENT":      1,
		"WEB":         2,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_fire_step_v1_session_domain_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_xyz_fire_step_v1_session_domain_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_session_domain_proto_rawDescGZIP(), []int{0}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Device        DeviceType             `protobuf:"varint,3,opt,name=device,proto3,enum=xyz.fire_step.v1.session.DeviceType" json:"device,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lastSeenAt,proto3" json:"lastSeenAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_xyz_fire_step_v1_session_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_session_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_session_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Session) GetDevice() DeviceType {
	if x != nil {
		return x.Device
	}
	return DeviceType_UNSPECIFIED
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Session) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type Sessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Session             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sessions) Reset() {
	*x = Sessions{}
	mi := &file_xyz_fire_step_v1_session_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sessions) ProtoMessage() {}

func (x *Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_session_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sessions.ProtoReflect.Descriptor instead.
func (*Sessions) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_session_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Sessions) GetList() []*Session {
	if x != nil {
		return x.List
	}
	return nil
}

var File_xyz_fire_step_v1_session_domain_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_session_domain_proto_rawDesc = "" +
	"\n" +
	"%xyz/fire-step/v1/session/domain.proto\x12\x18xyz.fire_step.v1.session\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\tR\aownerId\x12<\n" +
	"\x06device\x18\x03 \x01(\x0e2$.xyz.fire_step.v1.session.DeviceTypeR\x06device\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\texpiresAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\n" +
	"lastSeenAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"A\n" +
	"\bSessions\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.xyz.fire_step.v1.session.SessionR\x04list*2\n" +
	"\n" +
	"DeviceType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x01\x12\a\n" +
	"\x03WEB\x10\x02BzZTgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/session;session\xaa\x02!Aesterial.FireStep.Api.V1.Sessionb\x06proto3"

var (
	file_xyz_fire_step_v1_session_domain_proto_rawDescOnce sync.Once
	file_xyz_fire_step_v1_session_domain_proto_rawDescData []byte
)

func file_xyz_fire_step_v1_session_domain_proto_rawDescGZIP() []byte {
	file_xyz_fire_step_v1_session_domain_proto_rawDescOnce.Do(func() {
		file_xyz_fire_step_v1_session_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_session_domain_proto_rawDesc), len(file_xyz_fire_step_v1_session_domain_proto_rawDesc)))
	})
	return file_xyz_fire_step_v1_session_domain_proto_rawDescData
}

var file_xyz_fire_step_v1_session_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_fire_step_v1_session_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xyz_fire_step_v1_session_domain_proto_goTypes = []any{
	(DeviceType)(0),               // 0: xyz.fire_step.v1.session.DeviceType
	(*Session)(nil),               // 1: xyz.fire_step.v1.session.Session
	(*Sessions)(nil),              // 2: xyz.fire_step.v1.session.Sessions
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_xyz_fire_step_v1_session_domain_proto_depIdxs = []int32{
	0, // 0: xyz.fire_step.v1.session.Session.device:type_name -> xyz.fire_step.v1.session.DeviceType
	3, // 1: xyz.fire_step.v1.session.Session.createdAt:type_name -> google.protobuf.Timestamp
	3, // 2: xyz.fire_step.v1.session.Session.expiresAt:type_name -> google.protobuf.Timestamp
	3, // 3: xyz.fire_step.v1.session.Session.lastSeenAt:type_name -> google.protobuf.Timestamp
	1, // 4: xyz.fire_step.v1.session.Sessions.list:type_name -> xyz.fire_step.v1.session.Session
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_session_domain_proto_init() }
func file_xyz_fire_step_v1_session_domain_proto_init() {
	if File_xyz_fire_step_v1_session_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_session_domain_proto_rawDesc), len(file_xyz_fire_step_v1_session_domain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_fire_step_v1_session_domain_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_session_domain_proto_depIdxs,
		EnumInfos:         file_xyz_fire_step_v1_session_domain_proto_enumTypes,
		MessageInfos:      file_xyz_fire_step_v1_session_domain_proto_msgTypes,
	}.Build()
	File_xyz_fire_step_v1_session_domain_proto = out.File
	file_xyz_fire_step_v1_session_domain_proto_goTypes = nil
	file_xyz_fire_step_v1_session_domain_proto_depIdxs = nil
}
