// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xyz/fire-step/v1/session/service.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_xyz_fire_step_v1_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_fire_step_v1_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_xyz_fire_step_v1_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_xyz_fire_step_v1_session_service_proto protoreflect.FileDescriptor

const file_xyz_fire_step_v1_session_service_proto_rawDesc = "" +
	"\n" +
	"&xyz/fire-step/v1/session/service.proto\x12\x18xyz.fire_step.v1.session\x1a\x1bgoogle/protobuf/empty.proto\x1a%xyz/fire-step/v1/session/domain.proto\"&\n" +
	"\x14RevokeSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8f\x01\n" +
	"\x0fSessionsService\x12B\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\".xyz.fire_step.v1.session.Sessions\x128\n" +
	"\x06Revoke\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBzZTgithub.com/aesterial/fire-step/backend/internal/api/xyz/fire-step/v1/session;session\xaa\x02!Aesterial.FireStep.Api.V1.Sessionb\x06proto3"

var (
	file_xyz_fire_step_v1_session_service_proto_rawDescOnce sync.Once
	file_xyz_fire_step_v1_session_service_proto_rawDescData []byte
)

func file_xyz_fire_step_v1_session_service_proto_rawDescGZIP() []byte {
	file_xyz_fire_step_v1_session_service_proto_rawDescOnce.Do(func() {
		file_xyz_fire_step_v1_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_session_service_proto_rawDesc), len(file_xyz_fire_step_v1_session_service_proto_rawDesc)))
	})
	return file_xyz_fire_step_v1_session_service_proto_rawDescData
}

var file_xyz_fire_step_v1_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xyz_fire_step_v1_session_service_proto_goTypes = []any{
	(*RevokeSessionRequest)(nil), // 0: xyz.fire_step.v1.session.RevokeSessionRequest
	(*emptypb.Empty)(nil),        // 1: google.protobuf.Empty
	(*Sessions)(nil),             // 2: xyz.fire_step.v1.session.Sessions
}
var file_xyz_fire_step_v1_session_service_proto_depIdxs = []int32{
	1, // 0: xyz.fire_step.v1.session.SessionsService.List:input_type -> google.protobuf.Empty
	1, // 1: xyz.fire_step.v1.session.SessionsService.Revoke:input_type -> google.protobuf.Empty
	2, // 2: xyz.fire_step.v1.session.SessionsService.List:output_type -> xyz.fire_step.v1.session.Sessions
	1, // 3: xyz.fire_step.v1.session.SessionsService.Revoke:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xyz_fire_step_v1_session_service_proto_init() }
func file_xyz_fire_step_v1_session_service_proto_init() {
	if File_xyz_fire_step_v1_session_service_proto != nil {
		return
	}
	file_xyz_fire_step_v1_session_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xyz_fire_step_v1_session_service_proto_rawDesc), len(file_xyz_fire_step_v1_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xyz_fire_step_v1_session_service_proto_goTypes,
		DependencyIndexes: file_xyz_fire_step_v1_session_service_proto_depIdxs,
		MessageInfos:      file_xyz_fire_step_v1_session_service_proto_msgTypes,
	}.Build()
	File_xyz_fire_step_v1_session_service_proto = out.File
	file_xyz_fire_step_v1_session_service_proto_goTypes = nil
	file_xyz_fire_step_v1_session_service_proto_depIdxs = nil
}
