// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceType string

const (
	DeviceTypeWeb    DeviceType = "web"
	DeviceTypeClient DeviceType = "client"
)

func (e *DeviceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceType(s)
	case string:
		*e = DeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceType: %T", src)
	}
	return nil
}

type NullDeviceType struct {
	DeviceType DeviceType `json:"device_type"`
	Valid      bool       `json:"valid"` // Valid is true if DeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceType) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceType), nil
}

type Seance struct {
	ID      pgtype.UUID        `json:"id"`
	Owner   pgtype.UUID        `json:"owner"`
	Errors  int32              `json:"errors"`
	Actions []byte             `json:"actions"`
	At      pgtype.Timestamptz `json:"at"`
	Done    pgtype.Timestamptz `json:"done"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	Owner      pgtype.UUID        `json:"owner"`
	Device     DeviceType         `json:"device"`
	Createdat  pgtype.Timestamptz `json:"createdat"`
	Expiresat  pgtype.Timestamptz `json:"expiresat"`
	Lastseenat pgtype.Timestamptz `json:"lastseenat"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Initials    string             `json:"initials"`
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	Org         string             `json:"org"`
	AdminAccess bool               `json:"admin_access"`
	Joinedat    pgtype.Timestamptz `json:"joinedat"`
}
