// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions (owner, device)
values ($1, $2)
returning id, owner, device, createdat, expiresat, lastSeenAt
`

type CreateSessionParams struct {
	Owner  pgtype.UUID `json:"owner"`
	Device DeviceType  `json:"device"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Owner, arg.Device)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Device,
		&i.Createdat,
		&i.Expiresat,
		&i.Lastseenat,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (username, email, password, org, initials)
values ($1, $2, $3, $4, $5)
returning id, username, initials, email, org, admin_access, joinedat
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Org      string `json:"org"`
	Initials string `json:"initials"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Initials    string             `json:"initials"`
	Email       string             `json:"email"`
	Org         string             `json:"org"`
	AdminAccess bool               `json:"admin_access"`
	Joinedat    pgtype.Timestamptz `json:"joinedat"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Org,
		arg.Initials,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Initials,
		&i.Email,
		&i.Org,
		&i.AdminAccess,
		&i.Joinedat,
	)
	return i, err
}

const createUserSeance = `-- name: CreateUserSeance :one
insert into seance (owner, actions, at, done, errors)
values ($1, $2, $3, $4, $5)
returning id, owner, errors, actions, at, done
`

type CreateUserSeanceParams struct {
	Owner   pgtype.UUID        `json:"owner"`
	Actions []byte             `json:"actions"`
	At      pgtype.Timestamptz `json:"at"`
	Done    pgtype.Timestamptz `json:"done"`
	Errors  int32              `json:"errors"`
}

func (q *Queries) CreateUserSeance(ctx context.Context, arg CreateUserSeanceParams) (Seance, error) {
	row := q.db.QueryRow(ctx, createUserSeance,
		arg.Owner,
		arg.Actions,
		arg.At,
		arg.Done,
		arg.Errors,
	)
	var i Seance
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Errors,
		&i.Actions,
		&i.At,
		&i.Done,
	)
	return i, err
}

const getActivityByDayByOrg = `-- name: GetActivityByDayByOrg :many
SELECT date_trunc('day', at)::timestamptz AS day, COUNT(s.id)::int AS count
FROM seance s
         JOIN users u ON u.id = s.owner
WHERE u.org = $1 AND at > NOW() - INTERVAL '7 days'
GROUP BY day
ORDER BY day
`

type GetActivityByDayByOrgRow struct {
	Day   pgtype.Timestamptz `json:"day"`
	Count int32              `json:"count"`
}

func (q *Queries) GetActivityByDayByOrg(ctx context.Context, org string) ([]GetActivityByDayByOrgRow, error) {
	rows, err := q.db.Query(ctx, getActivityByDayByOrg, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActivityByDayByOrgRow{}
	for rows.Next() {
		var i GetActivityByDayByOrgRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getErrorsPerHourByOrg = `-- name: GetErrorsPerHourByOrg :many
SELECT date_trunc('hour', at)::timestamptz AS hour, SUM(errors)::int AS count
FROM seance s
         JOIN users u ON u.id = s.owner
WHERE u.org = $1 AND at > NOW() - INTERVAL '24 hours'
GROUP BY hour
ORDER BY hour
`

type GetErrorsPerHourByOrgRow struct {
	Hour  pgtype.Timestamptz `json:"hour"`
	Count int32              `json:"count"`
}

func (q *Queries) GetErrorsPerHourByOrg(ctx context.Context, org string) ([]GetErrorsPerHourByOrgRow, error) {
	rows, err := q.db.Query(ctx, getErrorsPerHourByOrg, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetErrorsPerHourByOrgRow{}
	for rows.Next() {
		var i GetErrorsPerHourByOrgRow
		if err := rows.Scan(&i.Hour, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSeancesByOrg = `-- name: GetLatestSeancesByOrg :many
SELECT s.id, s.owner, s.errors, s.actions, s.at, s.done
FROM seance s
         JOIN users u ON u.id = s.owner
WHERE u.org = $1
ORDER BY s.at DESC
LIMIT 7
`

func (q *Queries) GetLatestSeancesByOrg(ctx context.Context, org string) ([]Seance, error) {
	rows, err := q.db.Query(ctx, getLatestSeancesByOrg, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seance{}
	for rows.Next() {
		var i Seance
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Errors,
			&i.Actions,
			&i.At,
			&i.Done,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordByUsername = `-- name: GetPasswordByUsername :one
select password
from users
where username = $1
limit 1
`

func (q *Queries) GetPasswordByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordByUsername, username)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getSeanceStatsByOrg = `-- name: GetSeanceStatsByOrg :one
SELECT COUNT(s.id)                              AS total_seances,
       COALESCE(SUM(s.errors), 0)               AS total_errors,
       AVG(EXTRACT(EPOCH FROM (s.done - s.at))) AS avg_execution_time_seconds
FROM seance s
         JOIN users u ON u.id = s.owner
WHERE u.org = $1
`

type GetSeanceStatsByOrgRow struct {
	TotalSeances            int64       `json:"total_seances"`
	TotalErrors             interface{} `json:"total_errors"`
	AvgExecutionTimeSeconds float64     `json:"avg_execution_time_seconds"`
}

func (q *Queries) GetSeanceStatsByOrg(ctx context.Context, org string) (GetSeanceStatsByOrgRow, error) {
	row := q.db.QueryRow(ctx, getSeanceStatsByOrg, org)
	var i GetSeanceStatsByOrgRow
	err := row.Scan(&i.TotalSeances, &i.TotalErrors, &i.AvgExecutionTimeSeconds)
	return i, err
}

const getSession = `-- name: GetSession :one
select id, owner, device, createdat, expiresat, lastseenat
from sessions
where id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Device,
		&i.Createdat,
		&i.Expiresat,
		&i.Lastseenat,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select username, email, org, initials, admin_access, joinedat
from users
where id = $1
`

type GetUserRow struct {
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Org         string             `json:"org"`
	Initials    string             `json:"initials"`
	AdminAccess bool               `json:"admin_access"`
	Joinedat    pgtype.Timestamptz `json:"joinedat"`
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.Org,
		&i.Initials,
		&i.AdminAccess,
		&i.Joinedat,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, email, org, initials, admin_access, joinedat
from users
where username = $1
limit 1
`

type GetUserByUsernameRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Org         string             `json:"org"`
	Initials    string             `json:"initials"`
	AdminAccess bool               `json:"admin_access"`
	Joinedat    pgtype.Timestamptz `json:"joinedat"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Org,
		&i.Initials,
		&i.AdminAccess,
		&i.Joinedat,
	)
	return i, err
}

const getUserSeances = `-- name: GetUserSeances :many
select id, owner, errors, actions, at, done
from seance
where owner = $1
`

func (q *Queries) GetUserSeances(ctx context.Context, owner pgtype.UUID) ([]Seance, error) {
	rows, err := q.db.Query(ctx, getUserSeances, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seance{}
	for rows.Next() {
		var i Seance
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Errors,
			&i.Actions,
			&i.At,
			&i.Done,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrg = `-- name: GetUsersByOrg :many
select id, email, username, initials, admin_access, joinedat
from users
where org = $1
`

type GetUsersByOrgRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Username    string             `json:"username"`
	Initials    string             `json:"initials"`
	AdminAccess bool               `json:"admin_access"`
	Joinedat    pgtype.Timestamptz `json:"joinedat"`
}

func (q *Queries) GetUsersByOrg(ctx context.Context, org string) ([]GetUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUsersByOrg, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByOrgRow{}
	for rows.Next() {
		var i GetUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Initials,
			&i.AdminAccess,
			&i.Joinedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersCountByOrg = `-- name: GetUsersCountByOrg :one
select count(*)
from users
where org = $1
`

func (q *Queries) GetUsersCountByOrg(ctx context.Context, org string) (int64, error) {
	row := q.db.QueryRow(ctx, getUsersCountByOrg, org)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isSessionExists = `-- name: IsSessionExists :one
select exists (select 1 from sessions where id = $1)
`

func (q *Queries) IsSessionExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
select admin_access
from users
where id = $1
limit 1
`

func (q *Queries) IsUserAdmin(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdmin, id)
	var admin_access bool
	err := row.Scan(&admin_access)
	return admin_access, err
}

const isUserExists = `-- name: IsUserExists :one
select exists (select 1 from users where id = $1)
`

func (q *Queries) IsUserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUsernameOrEmailExists = `-- name: IsUsernameOrEmailExists :one
select exists (select 1 from users where username = $1 OR email = $2)
`

type IsUsernameOrEmailExistsParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) IsUsernameOrEmailExists(ctx context.Context, arg IsUsernameOrEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUsernameOrEmailExists, arg.Username, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions
set expiresat = now()
where id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const sessionList = `-- name: SessionList :many
select id, owner, device, createdat, expiresat, lastSeenAt
from sessions
where owner = $1
`

func (q *Queries) SessionList(ctx context.Context, owner pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionList, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Device,
			&i.Createdat,
			&i.Expiresat,
			&i.Lastseenat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionOwner = `-- name: SessionOwner :one
select owner
from sessions
where id = $1
limit 1
`

func (q *Queries) SessionOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sessionOwner, id)
	var owner pgtype.UUID
	err := row.Scan(&owner)
	return owner, err
}

const setSessionLastSeen = `-- name: SetSessionLastSeen :exec
update sessions
set lastseenat = $1
where id = $2
`

type SetSessionLastSeenParams struct {
	Lastseenat pgtype.Timestamptz `json:"lastseenat"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) SetSessionLastSeen(ctx context.Context, arg SetSessionLastSeenParams) error {
	_, err := q.db.Exec(ctx, setSessionLastSeen, arg.Lastseenat, arg.ID)
	return err
}
