// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserSeance(ctx context.Context, arg CreateUserSeanceParams) (Seance, error)
	GetPasswordByUsername(ctx context.Context, username string) (string, error)
	GetSeanceStatsByOrg(ctx context.Context, org string) (GetSeanceStatsByOrgRow, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserSeances(ctx context.Context, owner pgtype.UUID) ([]Seance, error)
	GetUsersByOrg(ctx context.Context, org string) ([]GetUsersByOrgRow, error)
	GetUsersCountByOrg(ctx context.Context, org string) (int64, error)
	IsSessionExists(ctx context.Context, id pgtype.UUID) (bool, error)
	IsUserAdmin(ctx context.Context, id pgtype.UUID) (bool, error)
	IsUserExists(ctx context.Context, id pgtype.UUID) (bool, error)
	IsUsernameOrEmailExists(ctx context.Context, arg IsUsernameOrEmailExistsParams) (bool, error)
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	SessionList(ctx context.Context, owner pgtype.UUID) ([]Session, error)
	SessionOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	SetSessionLastSeen(ctx context.Context, arg SetSessionLastSeenParams) error
}

var _ Querier = (*Queries)(nil)
